# Generated by Django 4.1.2 on 2022-11-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roommember",
            name="emoji",
            field=models.CharField(default="👙", max_length=2),
        ),
    ]
