# Generated by Django 4.1.2 on 2022-11-14 22:37

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_roommember_emoji"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roommember",
            name="emoji",
            field=models.CharField(default=chat.models.default_emoji, max_length=2),
        ),
    ]
