# Generated by Django 4.1.2 on 2022-10-24 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('category', models.CharField(blank=True, choices=[('Movie Titles', 'Movie Titles'), ('Song Titles', 'Song Titles'), ('Pop Culture', 'Pop Culture'), ('Miscellaneous', 'Miscellaneous')], max_length=50, null=True)),
                ('hints', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('prompt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prompts.prompt')),
            ],
        ),
    ]
