# Generated by Django 4.1.2 on 2022-10-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='connection_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prompt',
            name='category',
            field=models.CharField(blank=True, choices=[('Movie Titles', 'Movie Titles'), ('Song Titles', 'Song Titles'), ('Pop Culture', 'Pop Culture'), ('Miscellaneous', 'Miscellaneous'), ('Idioms', 'Idioms')], max_length=50, null=True),
        ),
    ]
