# Generated by Django 4.1.2 on 2022-10-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_room_connection_count_alter_prompt_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='connection_count',
            field=models.IntegerField(default=0),
        ),
    ]
