# Generated by Django 4.1.2 on 2022-10-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0005_roommember'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='end_of_round_count',
            field=models.IntegerField(default=0),
        ),
    ]
