# Generated by Django 4.1.2 on 2022-10-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0007_rename_end_of_round_count_room_end_of_round_reached_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_round',
            field=models.IntegerField(default=0),
        ),
    ]
