# Generated by Django 4.1.2 on 2022-10-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0008_room_current_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='_leader',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
