# Generated by Django 4.1.2 on 2022-10-28 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0009_room__leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='connection_count',
        ),
    ]
